### ISSUE TITLE
darwin-arm64 生成了一个exe，在macOS-arm64环境下无法运行

### ISSUE THREAD

**Issue by ryuujo1573** [natfrp/auth-guest#1]
<img width="487" alt="image" src="https://user-images.githubusercontent.com/16525512/160268186-b4ac59dd-399a-492d-8e0e-8e6034b83e51.png">

**Comment by fakeboboliu** [comment]
生成文件名默认是 exe 这件事符合我的预期，因为这个工具准备时首先考虑了 windows 用户的认知

使用其他系统的用户应该都知道 ext 和实际的内容并没有什么关联，尤其是黑苹果用户，考虑到应该造成不了什么问题就没有处理

文档中已经提供了一些示例的 shell 脚本，对于类 Unix 用户来说，改改那个会比下个二进制更简单一些

至于运行的事，只能说 title 和 issue 内容不符，所以在获得补充信息前我也不知道这是什么问题

**Comment by ryuujo1573** [comment]
shell脚本没有问题，这个生成的脚本在这边环境无法使用

Darwin 21.1.0 Darwin Kernel Version 21.1.0: Wed Oct 13 17:33:24 PDT 2021; root:xnu-8019.41.5~1/RELEASE_ARM64_T8101 arm64

**Comment by fakeboboliu** [comment]
> Legion-R7000P

> arm64

？

**Comment by ryuujo1573** [comment]
> > Legion-R7000P
> 
> > arm64
> 
> ？

哈哈哈哈哈哈哈哈我的设备名叫Legion-R7000P，是AArch64 m1的macbook

**Comment by fakeboboliu** [comment]
感谢您的反馈，我们在 https://github.com/natfrp/wiki/commit/474c455871cc3d1441d3d812a066c9d4d7503857 中补充了关于此问题的解决方案
